# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(492, 452)
        self.horizontalLayout = QtWidgets.QHBoxLayout(LoginForm)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_3 = QtWidgets.QWidget(LoginForm)
        self.widget_3.setStyleSheet("QPushButton#pushButton, #pushButton_6{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#pushButton:hover, #pushButton_6:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed, #pushButton_6:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}\n"
"\n"
"QPushButton#pushButton_2, #pushButton_3, #pushButton_4, #pushButton_5{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    color:rgba(85, 98, 112, 255);\n"
"}\n"
"\n"
"QPushButton#pushButton_2:hover, #pushButton_3:hover, #pushButton_4:hover, #pushButton_5:hover{\n"
"    color: rgba(131, 96, 53, 255);\n"
"}\n"
"\n"
"QPushButton#pushButton_2:pressed, #pushButton_3:pressed, #pushButton_4:pressed, #pushButton_5:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    color:rgba(91, 88, 53, 255);\n"
"}\n"
"\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 280, 430))
        self.label_8.setStyleSheet("background-color:rgba(2, 65, 118, 255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"border-top-left-radius: 50px;")
        self.label_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setGeometry(QtCore.QRect(230, 0, 240, 430))
        self.label_7.setStyleSheet("background-color:rgba(255, 255, 255, 255);\n"
"border-bottom-right-radius: 50px;")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_11 = QtWidgets.QLabel(self.widget_3)
        self.label_11.setGeometry(QtCore.QRect(0, 50, 230, 130))
        self.label_11.setStyleSheet("background-color:rgba(0, 0, 0, 75);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setGeometry(QtCore.QRect(0, 50, 231, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgba(255, 255, 255, 200);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widget_3)
        self.label_10.setGeometry(QtCore.QRect(0, 140, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:rgba(255, 255, 255, 170);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setGeometry(QtCore.QRect(240, 40, 220, 315))
        self.widget_4.setObjectName("widget_4")
        self.label_14 = QtWidgets.QLabel(self.widget_4)
        self.label_14.setGeometry(QtCore.QRect(0, 10, 221, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color:rgba(0, 0, 0, 200);")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.lineEdit_eposta_2 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_eposta_2.setGeometry(QtCore.QRect(20, 110, 190, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_eposta_2.setFont(font)
        self.lineEdit_eposta_2.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.lineEdit_eposta_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_eposta_2.setObjectName("lineEdit_eposta_2")
        self.lineEdit_sifre_2 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_sifre_2.setGeometry(QtCore.QRect(20, 160, 190, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_sifre_2.setFont(font)
        self.lineEdit_sifre_2.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.lineEdit_sifre_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_sifre_2.setObjectName("lineEdit_sifre_2")
        self.pushButton_giris = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_giris.setGeometry(QtCore.QRect(10, 230, 201, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_giris.setFont(font)
        self.pushButton_giris.setStyleSheet("QPushButton#pushButton_giris {\n"
"    background-color: rgba(2, 65, 118, 255);\n"
"    color: rgba(255, 255, 255, 200);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#pushButton_giris:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(2, 65, 118, 100);\n"
"    background-position: calc(100% - 10px) center;\n"
"}")
        self.pushButton_giris.setObjectName("pushButton_giris")
        self.pushButton_kayitol = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_kayitol.setGeometry(QtCore.QRect(130, 280, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_kayitol.setFont(font)
        self.pushButton_kayitol.setStyleSheet("QPushButton#pushButton_kayitol {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#pushButton_kayitol:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(2, 65, 118, 100);\n"
"    background-position: calc(100% - 10px) center;\n"
"}\n"
"\n"
"QPushButton#pushButton_kayitol:hover {\n"
"    color: rgba(2, 65, 118, 255); /* İlk arka plan için kullanılan koyu mavi renk */\n"
"}")
        self.pushButton_kayitol.setObjectName("pushButton_kayitol")
        self.label_13 = QtWidgets.QLabel(self.widget_4)
        self.label_13.setGeometry(QtCore.QRect(20, 280, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("QLabel#pushButton{\n"
"background-color:rgba(2, 65, 118, 255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"@PushButton#pushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"background-position:calc(100% - 10px)center;\n"
"}\n"
"QLabel#pushButton{\n"
"background-color:rgba(2,65,118,200);\n"
"}")
        self.label_13.setObjectName("label_13")
        self.commandLinkButton_sifremiunuttum = QtWidgets.QCommandLinkButton(self.widget_3)
        self.commandLinkButton_sifremiunuttum.setGeometry(QtCore.QRect(230, 390, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setItalic(False)
        self.commandLinkButton_sifremiunuttum.setFont(font)
        self.commandLinkButton_sifremiunuttum.setStyleSheet("QCommandLinkButton#commandLinkButton_sifremiunuttum {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: none;\n"
"}\n"
"\n"
"QCommandLinkButton#commandLinkButton_sifremiunuttum:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(2, 65, 118, 100);\n"
"    background-position: calc(100% - 10px) center;\n"
"}\n"
"\n"
"QCommandLinkButton#commandLinkButton_sifremiunuttum:hover {\n"
"    color: rgba(2, 65, 118, 255); /* İlk arka plan için kullanılan koyu mavi renk */\n"
"}")
        self.commandLinkButton_sifremiunuttum.setObjectName("commandLinkButton_sifremiunuttum")
        self.label_12 = QtWidgets.QLabel(self.widget_3)
        self.label_12.setGeometry(QtCore.QRect(0, 380, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(6)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:rgba(255, 255, 255, 170);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_8.raise_()
        self.label_7.raise_()
        self.label_11.raise_()
        self.label_10.raise_()
        self.widget_4.raise_()
        self.commandLinkButton_sifremiunuttum.raise_()
        self.label_12.raise_()
        self.label_9.raise_()
        self.horizontalLayout.addWidget(self.widget_3)

        self.retranslateUi(LoginForm)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "Form"))
        self.label_9.setText(_translate("LoginForm", "TO DO LIST"))
        self.label_10.setText(_translate("LoginForm", "Gününüzü rahatça planlayın!"))
        self.label_14.setText(_translate("LoginForm", "GİRİŞ"))
        self.lineEdit_eposta_2.setPlaceholderText(_translate("LoginForm", "  E-posta"))
        self.lineEdit_sifre_2.setPlaceholderText(_translate("LoginForm", "  Şifre"))
        self.pushButton_giris.setText(_translate("LoginForm", "Giriş"))
        self.pushButton_kayitol.setText(_translate("LoginForm", "Kayıt Ol"))
        self.label_13.setText(_translate("LoginForm", "Üye değil misin?"))
        self.commandLinkButton_sifremiunuttum.setText(_translate("LoginForm", "Şifremi unuttum"))
        self.label_12.setText(_translate("LoginForm", "Acar Software™ © 2024 Tüm hakları saklıdır."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginForm = QtWidgets.QWidget()
    ui = Ui_LoginForm()
    ui.setupUi(LoginForm)
    LoginForm.show()
    sys.exit(app.exec_())
