# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'password.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PasswordForm(object):
    def setupUi(self, PasswordForm):
        PasswordForm.setObjectName("PasswordForm")
        PasswordForm.resize(372, 241)
        self.horizontalLayout = QtWidgets.QHBoxLayout(PasswordForm)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_5 = QtWidgets.QWidget(PasswordForm)
        self.widget_5.setStyleSheet("QPushButton#pushButton, #pushButton_6{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#pushButton:hover, #pushButton_6:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed, #pushButton_6:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}\n"
"\n"
"QPushButton#pushButton_2, #pushButton_3, #pushButton_4, #pushButton_5{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    color:rgba(85, 98, 112, 255);\n"
"}\n"
"\n"
"QPushButton#pushButton_2:hover, #pushButton_3:hover, #pushButton_4:hover, #pushButton_5:hover{\n"
"    color: rgba(131, 96, 53, 255);\n"
"}\n"
"\n"
"QPushButton#pushButton_2:pressed, #pushButton_3:pressed, #pushButton_4:pressed, #pushButton_5:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    color:rgba(91, 88, 53, 255);\n"
"}\n"
"\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.label_15 = QtWidgets.QLabel(self.widget_5)
        self.label_15.setGeometry(QtCore.QRect(0, 0, 351, 221))
        self.label_15.setStyleSheet("background-color:rgba(255, 255, 255, 255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"border-top-left-radius: 50px;\n"
"border-bottom-right-radius: 50px;")
        self.label_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.widget_6 = QtWidgets.QWidget(self.widget_5)
        self.widget_6.setGeometry(QtCore.QRect(0, 0, 351, 221))
        self.widget_6.setObjectName("widget_6")
        self.lineEdit_yenisifre = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_yenisifre.setGeometry(QtCore.QRect(20, 110, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_yenisifre.setFont(font)
        self.lineEdit_yenisifre.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.lineEdit_yenisifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_yenisifre.setObjectName("lineEdit_yenisifre")
        self.lineEdit_yenisifretekrar = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_yenisifretekrar.setGeometry(QtCore.QRect(20, 160, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_yenisifretekrar.setFont(font)
        self.lineEdit_yenisifretekrar.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.lineEdit_yenisifretekrar.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_yenisifretekrar.setObjectName("lineEdit_yenisifretekrar")
        self.lineEdit_guvenlikkodu = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_guvenlikkodu.setGeometry(QtCore.QRect(180, 110, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_guvenlikkodu.setFont(font)
        self.lineEdit_guvenlikkodu.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.lineEdit_guvenlikkodu.setText("")
        self.lineEdit_guvenlikkodu.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_guvenlikkodu.setObjectName("lineEdit_guvenlikkodu")
        self.pushButton_onayla = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_onayla.setGeometry(QtCore.QRect(180, 160, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_onayla.setFont(font)
        self.pushButton_onayla.setStyleSheet("QPushButton#pushButton_onayla {\n"
"    background-color: rgba(2, 65, 118, 255); /* Mavi arkaplan */\n"
"    color: white; /* Beyaz yazı rengi */\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#pushButton_onayla:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(2, 65, 118, 100);\n"
"    background-position: calc(100% - 10px) center;\n"
"}\n"
"\n"
"QPushButton#pushButton_onayla:hover {\n"
"    background-color: rgba(2, 65, 118, 150); /* İmleç üstüne gelindiğinde hafif ton farkı */\n"
"}")
        self.pushButton_onayla.setObjectName("pushButton_onayla")
        self.label_16 = QtWidgets.QLabel(self.widget_6)
        self.label_16.setGeometry(QtCore.QRect(0, 0, 351, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color:rgba(0, 0, 0, 200);")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.lineEdit_eposta3 = QtWidgets.QLineEdit(self.widget_6)
        self.lineEdit_eposta3.setGeometry(QtCore.QRect(20, 59, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_eposta3.setFont(font)
        self.lineEdit_eposta3.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.lineEdit_eposta3.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_eposta3.setObjectName("lineEdit_eposta3")
        self.horizontalLayout.addWidget(self.widget_5)

        self.retranslateUi(PasswordForm)
        QtCore.QMetaObject.connectSlotsByName(PasswordForm)

    def retranslateUi(self, PasswordForm):
        _translate = QtCore.QCoreApplication.translate
        PasswordForm.setWindowTitle(_translate("PasswordForm", "Form"))
        self.lineEdit_yenisifre.setPlaceholderText(_translate("PasswordForm", "  Yeni Şifre"))
        self.lineEdit_yenisifretekrar.setPlaceholderText(_translate("PasswordForm", "  Yeni Şifre Tekrar"))
        self.lineEdit_guvenlikkodu.setPlaceholderText(_translate("PasswordForm", "  Güvenlik Kodu"))
        self.pushButton_onayla.setText(_translate("PasswordForm", "Onayla"))
        self.label_16.setText(_translate("PasswordForm", "Şifrenizi Belirleyin"))
        self.lineEdit_eposta3.setPlaceholderText(_translate("PasswordForm", "  E-posta"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PasswordForm = QtWidgets.QWidget()
    ui = Ui_PasswordForm()
    ui.setupUi(PasswordForm)
    PasswordForm.show()
    sys.exit(app.exec_())
