# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterForm(object):
    def setupUi(self, RegisterForm):
        RegisterForm.setObjectName("RegisterForm")
        RegisterForm.setEnabled(True)
        RegisterForm.resize(492, 452)
        self.verticalLayout = QtWidgets.QVBoxLayout(RegisterForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_1 = QtWidgets.QWidget(RegisterForm)
        self.widget_1.setStyleSheet("QPushButton#pushButton, #pushButton_6{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#pushButton:hover, #pushButton_6:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed, #pushButton_6:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}\n"
"\n"
"QPushButton#pushButton_2, #pushButton_3, #pushButton_4, #pushButton_5{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    color:rgba(85, 98, 112, 255);\n"
"}\n"
"\n"
"QPushButton#pushButton_2:hover, #pushButton_3:hover, #pushButton_4:hover, #pushButton_5:hover{\n"
"    color: rgba(131, 96, 53, 255);\n"
"}\n"
"\n"
"QPushButton#pushButton_2:pressed, #pushButton_3:pressed, #pushButton_4:pressed, #pushButton_5:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    color:rgba(91, 88, 53, 255);\n"
"}\n"
"\n"
"")
        self.widget_1.setObjectName("widget_1")
        self.label_2 = QtWidgets.QLabel(self.widget_1)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 280, 430))
        self.label_2.setStyleSheet("background-color:rgba(2, 65, 118, 255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"border-top-left-radius: 50px;")
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_1 = QtWidgets.QLabel(self.widget_1)
        self.label_1.setGeometry(QtCore.QRect(230, 0, 240, 430))
        self.label_1.setStyleSheet("background-color:rgba(255, 255, 255, 255);\n"
"border-bottom-right-radius: 50px;")
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")
        self.label_5 = QtWidgets.QLabel(self.widget_1)
        self.label_5.setGeometry(QtCore.QRect(0, 50, 230, 130))
        self.label_5.setStyleSheet("background-color:rgba(0, 0, 0, 75);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.widget_1)
        self.label_3.setGeometry(QtCore.QRect(0, 50, 231, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgba(255, 255, 255, 200);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_1)
        self.label_4.setGeometry(QtCore.QRect(0, 140, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgba(255, 255, 255, 170);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.widget_2 = QtWidgets.QWidget(self.widget_1)
        self.widget_2.setGeometry(QtCore.QRect(240, 40, 220, 381))
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(0, 10, 221, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgba(0, 0, 0, 200);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit_eposta = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_eposta.setGeometry(QtCore.QRect(20, 110, 190, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_eposta.setFont(font)
        self.lineEdit_eposta.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.lineEdit_eposta.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_eposta.setObjectName("lineEdit_eposta")
        self.lineEdit_sifre = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_sifre.setGeometry(QtCore.QRect(20, 160, 190, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_sifre.setFont(font)
        self.lineEdit_sifre.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.lineEdit_sifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_sifre.setObjectName("lineEdit_sifre")
        self.lineEdit_ad = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_ad.setGeometry(QtCore.QRect(20, 60, 81, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_ad.setFont(font)
        self.lineEdit_ad.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.lineEdit_ad.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_ad.setObjectName("lineEdit_ad")
        self.lineEdit_soyad = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_soyad.setGeometry(QtCore.QRect(130, 60, 81, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_soyad.setFont(font)
        self.lineEdit_soyad.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.lineEdit_soyad.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_soyad.setObjectName("lineEdit_soyad")
        self.lineEdit_sifretekrar = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_sifretekrar.setGeometry(QtCore.QRect(20, 210, 190, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_sifretekrar.setFont(font)
        self.lineEdit_sifretekrar.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.lineEdit_sifretekrar.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_sifretekrar.setObjectName("lineEdit_sifretekrar")
        self.pushButton_kayitol_2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_kayitol_2.setGeometry(QtCore.QRect(10, 330, 201, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_kayitol_2.setFont(font)
        self.pushButton_kayitol_2.setStyleSheet("QPushButon#pushButton_kayitol_2{\n"
"background-color:rgba(2, 65, 118, 255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"@PushButton#pushButton_kayitol_2:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"background-position:calc(100% - 10px)center;\n"
"}\n"
"QPushButton#pushButton_kayitol_2{\n"
"background-color:rgba(0,0,0,25);\n"
"}")
        self.pushButton_kayitol_2.setObjectName("pushButton_kayitol_2")
        self.lineEdit_guvenlikkoduolustur = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_guvenlikkoduolustur.setGeometry(QtCore.QRect(20, 260, 191, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_guvenlikkoduolustur.setFont(font)
        self.lineEdit_guvenlikkoduolustur.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.lineEdit_guvenlikkoduolustur.setText("")
        self.lineEdit_guvenlikkoduolustur.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_guvenlikkoduolustur.setObjectName("lineEdit_guvenlikkoduolustur")
        self.bilgi_1 = QtWidgets.QLabel(self.widget_2)
        self.bilgi_1.setGeometry(QtCore.QRect(20, 300, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.bilgi_1.setFont(font)
        self.bilgi_1.setObjectName("bilgi_1")
        self.label_6 = QtWidgets.QLabel(self.widget_1)
        self.label_6.setGeometry(QtCore.QRect(0, 380, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(6)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgba(255, 255, 255, 170);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.widget_1)

        self.retranslateUi(RegisterForm)
        QtCore.QMetaObject.connectSlotsByName(RegisterForm)

    def retranslateUi(self, RegisterForm):
        _translate = QtCore.QCoreApplication.translate
        RegisterForm.setWindowTitle(_translate("RegisterForm", "Form"))
        self.label_3.setText(_translate("RegisterForm", "TO DO LIST"))
        self.label_4.setText(_translate("RegisterForm", "Gününüzü rahatça planlayın!"))
        self.label.setText(_translate("RegisterForm", "KAYIT OL"))
        self.lineEdit_eposta.setPlaceholderText(_translate("RegisterForm", "  E-posta"))
        self.lineEdit_sifre.setPlaceholderText(_translate("RegisterForm", "  Şifre"))
        self.lineEdit_ad.setPlaceholderText(_translate("RegisterForm", "  Ad"))
        self.lineEdit_soyad.setPlaceholderText(_translate("RegisterForm", "  Soyad"))
        self.lineEdit_sifretekrar.setPlaceholderText(_translate("RegisterForm", "  Şifre Tekrar"))
        self.pushButton_kayitol_2.setText(_translate("RegisterForm", "Kayıt Ol"))
        self.lineEdit_guvenlikkoduolustur.setPlaceholderText(_translate("RegisterForm", "  Güvenlik Kodu Oluştur"))
        self.bilgi_1.setText(_translate("RegisterForm", "*Şifreyi unuttuğunuzda bu kod sorulur."))
        self.label_6.setText(_translate("RegisterForm", "Acar Software™ © 2024 Tüm hakları saklıdır."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegisterForm = QtWidgets.QWidget()
    ui = Ui_RegisterForm()
    ui.setupUi(RegisterForm)
    RegisterForm.show()
    sys.exit(app.exec_())
